name: Publish npm package

on:
  push:
    branches: ['master']

defaults:
  run:
    working-directory: .

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write # GitHub Packagesへの書き込み権限が必要
      contents: read # リポジトリの内容の読み取り権限が必要

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com
      # MEMO: Github Actionsでnpm publishする場合は、手動でビルドしておく必要がある
      #       → Actions内でビルドしたdistを対象にnpm pubishしても実際に配置されるパッケージには反映されない
      #       → そのため、ビルド後のdistを対象にnpm publishするためのディレ
      #
      # - name: Install → ビルドを行うためdevDependenciesもインストールする
      #   run: npm install
      # - name: Build
      #   run: npm run build
      - name: publish npm package
        run: npm publish
        working-directory: pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
